trigger:
- '*'

pool:
  vmImage: ubuntu-latest
  
  
variables:
  - group: Blackduck

steps:        
- task: Bash@3
  displayName: Java Version
  env:
    JAVA_HOME: $(JAVA_HOME_11_X64)
    PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
  inputs:
    targetType: 'inline'
    script: |
       java -version
       
#- task: SynopsysDetectTask@9
#  inputs:
#    BlackDuckService: 'Blackduck_connection'
#    DetectVersion: 'latest'
- task: SynopsysSecurityScan@1
  displayName: 'Black Duck Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
  inputs:
    scanType: 'blackduck'
#    bridge_download_url: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/1.1.28/synopsys-bridge-1.1.28-macosx.zip"
    bridge_blackduck_url: 'https://vontier-matcotools.app.blackduck.com'
    bridge_blackduck_token: 'MjAwZjU2MTgtNzA5MS00MjM4LThhMDctMWM4NDE3MTZkN2YyOmE1YWJhOTQ1LTA3NDQtNDYyMC1iNTg3LWFmYzMzZjljMDNjOQ=='
    bridge_blackduck_scan_full: true
#    bridge_blackduck_fixpr_filter_severities: "CRITICAL,  HIGH"
#    bridge_blackduck_fixpr_enabled: true
#    bridge_blackduck_fixpr_maxCount: 2
#    bridge_blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
    include_diagnostics: true
    azure_token: $(System.AccessToken)
